# Generated by Django 3.2.5 on 2021-07-28 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'genres',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(default='Unknown', max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('user_rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('year', models.DecimalField(decimal_places=2, max_digits=4)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='store.genre')),
            ],
            options={
                'verbose_name_plural': 'Books',
                'ordering': ('user_rating',),
            },
        ),
    ]
