# Generated by Django 3.2.5 on 2021-07-28 19:34

from django.db import migrations

def import_data(apps, schema_editor):
    Book = apps.get_model('store', 'Book')
    

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
    ]
