# Generated by Django 3.2.5 on 2021-07-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_book_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='user_rating',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
    ]
