# Generated by Django 3.2.5 on 2021-07-30 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(default='unknown', max_length=255),
        ),
    ]
